<?php namespace Congresso\ModuloInscricao\Caravana\Repositorios;

use Congresso\ModuloInscricao\Caravana\Models\Caravana;
use Congresso\System\Repositorio\RepositorioAbstract;

class RepositorioCaravana extends RepositorioAbstract
{
    protected $caravana;

    public $connection;

    public function __construct(Caravana $caravana)
    {
        $this->caravana = $caravana;

        $this->connection = $this->caravana->connection;

        parent::__construct($this->caravana);
    }

    public function find($id)
    {
        return $this->caravana->join('municipios', 'municipios.muni_id', '=', 'caravana.cod_municipio')->where('cara_id', '=', $id)->first();
    }

    public function getWhere(array $input)
    {
        // TODO: Implement getWhere() method.
        $campos = [
            'cara_nome as nomeCaravana',
            'cara_responsavel as responsavelCaravana',
            'cara_telefone_responsavel as telefoneResponsavel',
            'municipios.muni_descricao as municipio',
            'cara_id as id'
        ];

        return $this->caravana->select($campos)
                              ->join('municipios', 'municipios.muni_id', '=', 'caravana.cod_municipio')
                              ->paginate(10);
    }

    public function save(array $input)
    {

        $this->caravana->cara_nome                  = $input['cara_nome'];
        $this->caravana->cara_responsavel           = $input['cara_responsavel'];
        $this->caravana->cod_municipio              = $input['cod_municipio'];
        $this->caravana->cara_telefone_responsavel  = $input['cara_telefone_responsavel'];
        $this->caravana->created_by                 = 2;

        $this->caravana->save();

        if(!$this->caravana->cara_id){
            throw new \AppException('Não foi possivel salvar o registro');
        }

        return $this->caravana; // TODO: Change the autogenerated stub
    }

    public function update(array $input)
    {
        return parent::update($input); // TODO: Change the autogenerated stub
    }

}