<?php namespace Congresso\ModuloInscricao\Participante\Repositorios;

use Congresso\ModuloInscricao\Participante\Models\Participante;
use Congresso\System\Repositorio\RepositorioAbstract;

class RepositorioApresentador extends RepositorioAbstract
{
    protected $participante;

    public function __construct(Participante $participante)
    {
        $this->participante = $participante;

        parent::__construct($this->participante);
    }

    public function update(array $input)
    {

        $this->participante = $this->participante->find($input['id']);

        if(!$this->participante){
            throw new \AppException('Não foi possivel localizar o participante solicitado');
        }

        $this->participante->part_apresentador = $input['part_apresentador'];

        $this->participante->save();

        if(!$this->participante->part_id){
            throw new \AppException('Não foi possivel salvar o registro');
        }

        return $this->participante; // TODO: Change the autogenerated stub
    }

    public function getWhere(array $input)
    {
        // TODO: Implement getWhere() method.
    }

}